[build]
  base = "frontend"
  publish = ".next"
  command = "npm run build"

[functions]
  directory = "netlify/functions"
  external_node_modules = ["express"]
  node_bundler = "esbuild"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true
